import os
import json
import pandas as pd
from dotenv import load_dotenv
from apify_client import ApifyClient
from urllib.parse import quote
import sys
import io

# Force UTF-8 encoding for standard output
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
load_dotenv()
client = ApifyClient(os.getenv("APIFY_TOKEN"))


def run_scout():
    # Load preferences from the JSON generated by resume.py
    with open("resume.json", "r") as f:
        data = json.load(f)

    job_title = data.get("target_role", "Software Engineer")
    location = data.get("preferred_location", "India")

    search_url = f"https://www.linkedin.com/jobs/search/?keywords={quote(job_title)}&location={quote(location)}&f_E=2"

    run_input = {
        "cookies": [
            {"domain": ".linkedin.com", "name": "li_at", "value": os.getenv("LI_AT_COOKIE")},
            {"domain": ".www.linkedin.com", "name": "JSESSIONID", "value": os.getenv("JSESSIONID_VALUE")}
        ],
        "searchUrl": search_url,
        "count": 10,
        "scrapeCompany": True,
        "scrapeSkills": True,
        "proxy": {"useApifyProxy": True}
    }

    print(f"🚀 Scraping LinkedIn for: {job_title}...")
    try:
        run = client.actor("curious_coder/linkedin-jobs-search-scraper").call(run_input=run_input)
        jobs = list(client.dataset(run["defaultDatasetId"]).iterate_items())
        pd.DataFrame(jobs).to_csv("found_jobs.csv", index=False)
        print("✅ Saved found_jobs.csv")
    except Exception as e:
        print(f"❌ Error: {e}")


if __name__ == "__main__":
    run_scout()